### PR TITLE
Remove unused code of zsh completion

### PR DESCRIPTION
**Pull request by Freed-Wu**
See <https://github.com/inducer/pudb/pull/554#issuecomment-1250708829> and
<https://github.com/inducer/pudb/pull/554#issuecomment-1250716904>,
the wrong `_comp_priv_prefix` must be removed.

### CODE REVIEW

**Comment by rofl0r** [comment]
when i merged the zsh completion i assumed this is a one-off favor, but this is now the 3rd edit. i don't want to clutter the git commit history with zsh completion changes and spend more time with it, so you get one last chance to get this right, else i will remove it again.
so take your time to make this the ultimate and final fix.

**Comment by Freed-Wu** [comment]
OK, wait for enough long time to ensure nothing wrong happen. (BTW, even if this change isn't merged, it will not affect anyone. This change does not fix a bug, just remove some unused code, so we can have enough time.)

And this script is not generated automatically (go/rust/python have libraries to generate shell completion script automatically), so if new option is added or old option has changed, the script should be changed manually, which is troublesome. It is the biggest weakness. Maybe something like <https://github.com/mirror/x264/blob/master/autocomplete.c> is a better method.

**Comment by rofl0r** [comment]
is this good to merge now ?

**Comment by Freed-Wu** [comment]
- I change the file path to completions/zsh/_proxychains, which should be less confused.
- Now it should be the final work.

**Comment by Freed-Wu** [comment]
@rofl0r

**Pull request merged**
