### PR TITLE
integrated quick-sort into `intsort` function

### PR DESCRIPTION
**Pull request by winterrdog**
## Description

This pull request introduces a hybrid sorting approach within the `intsort` function, combining both Selection Sort and Quick Sort algorithms. For small datasets (less than or equal to `25` elements), Selection Sort is utilized for its simplicity and efficiency. Conversely, for larger datasets, Quick Sort is employed to leverage its superior performance characteristics in case it's ever needed in future code commits.

## Reason:

- Optimal Performance: By utilizing Selection Sort for small datasets and Quick Sort for larger datasets, the `intsort` function achieves optimal performance across a wide range of input sizes. Selection Sort's efficiency for small datasets ensures quick sorting without overhead, while Quick Sort's superior performance scales efficiently for larger datasets.
- Scalability and Efficiency: The hybrid approach enhances the scalability and efficiency of the sorting function. It adapts dynamically to the size of the dataset, ensuring efficient sorting regardless of input size.

@rofl0r , Lemme know what you think about it?

### CODE REVIEW

**Comment by rofl0r** [comment]
this is total overkill, there are only 4 ints to be sorted - that's why i replaced the quicksort that was used in the original PR with a tiny intsort.

**Comment by rofl0r** [comment]
checking git history before filing a PR for the win: 
0a4daa62d6d7889e630428325e08dfe8e83caf5e

**Comment by winterrdog** [comment]
@rofl0r, that's alright! 

I just thought it'd be needed in the future for bigger arrays, but I get it. If it's just 4 elements, it'd b total overkill 🤝

Dropping the commit🫡

**Comment by rofl0r** [comment]
even if it was 50 ints, this is absolutely not performance sensitive. it's called only once on startup. the whole code of proxychains-ng is dominated by i/o syscalls, that's why it's built without optimization by default. it really doesn't matter whether proxychains spends 500 cycles per connect() call or 2000. both only take nanoseconds, vs milliseconds or even seconds spent on the wire.

**Comment by winterrdog** [comment]
Alright 👍 

I've taken note 📝 

Thanks for the clarification and insight 🤝🤝

**Pull request closed without merging**
