### PR TITLE
Dl_info is undeclared with uclibc-ng without __USE_GNU

### PR DESCRIPTION
**Pull request by fda77**
- like https://github.com/rofl0r/proxychains-ng/issues/338
 - refs https://github.com/wbx-github/uclibc-ng/blob/v1.0.44/include/dlfcn.h#L90
 - used https://github.com/Freetz-NG/freetz-ng/commit/3336514d8c5a49dd346432b68c0611be2ff37ea1

### CODE REVIEW

**Comment by rofl0r** [comment]
`__USE_GNU` is an internal macro, most likely set by features.h when `_GNU_SOURCE` or similar is used. the latter is the macro supposed to be used by the application.

**Comment by fda77** [comment]
Thx. I'm not much experienced in this.
By add  `-D_GNU_SOURCE` to `CFLAGS` and removing this patch/pr, compiling also works. Is this the better way? With older proxychains versions this was nothing needed
 `"_GNU_SOURCE" redefined` shows for https://github.com/rofl0r/proxychains-ng/blob/master/src/daemon/daemon.c#L8

**Comment by rofl0r** [comment]
it would be best to write a configure check for this, but unconditionally putting _GNU_SOURCE into CFLAGS or before including any header in the file using Dl_info should work too, though the BSDs sometimes become annoying when you enable gnu features.

**Comment by fda77** [comment]
Sorry, I can't help writing a configure script, but i can test if it works.
Meanwhile i'm using it this way: https://github.com/Freetz-NG/freetz-ng/commit/23cf5e65d95e7f0c1d6d2d05687c6f40a01fefe3

**Comment by fda77** [comment]
Sry, that was unexpected and i cant open it again due to missing permissions

**Comment by rofl0r** [comment]
i can't either but i guess it's OK. uclibc is dying out, but if other users come across this error they should find this via a search engine.

**Comment by rofl0r** [comment]
> 15 May 2012, uClibc 0.9.33.2 Released 

are you refering to uclibc-ng ?

**Comment by rofl0r** [comment]
@wbx-github maybe uclibc-ng can be made to expose this using the same feature test macros than glibc ?

**Pull request closed without merging**
