### PR TITLE
Fix missing struct members `s6_addr32' and `s6_addr16' on OSX.

### PR DESCRIPTION
**Pull request by jaytaylor**
Like FreeBSD, `in6_addr` doesn't have a struct member called `s6_addr32' or
`s6_add16' on Mac OS X.

This commit adds OSX to the controlled group that replaces:

    `s6_addr32' with `__u6_addr.__u6_addr32'
    `s6_addr16' with `__u6_addr.__u6_addr16'

Sample of errors thrown:

```
src/libproxychains.c:332:12: error: no member named 's6_addr32' in 'struct in6_addr'
        return a->s6_addr32[0] == 0 && a->s6_addr32[1] == 0 &&
               ~  ^

src/libproxychains.c:337:36: error: no member named 's6_addr16' in 'struct in6_addr'
               a->s6_addr16[4] == 0 && a->s6_addr16[5] == 0xffff;
                                       ~  ^
```

For further explanation also see this PassiveDNS project commit:

https://github.com/gamelinux/passivedns/commit/42dbd6c5ae8bf4b6bcac38e0a5de41448b8ad777

### CODE REVIEW

**Comment by rofl0r** [comment]
uhm. how did you build proxychains-ng ? it has a configure check so we don't have to hardcode a list of currently broken systems into the code.
generally if you need to `#ifdef __SOME_SYSTEM` you're doing something wrong: you're assuming SOME_SYSTEM will never change. therefore you should check whether the system you build on uses s6_addr32 or __u6_addr.__u6_addr32 - exactly what we already do.

**Comment by jaytaylor** [comment]
I just followed the INSTALL instructions.

    ./configure
    make # <- broke here

**Comment by rofl0r** [comment]
what's the output of configure ?

**Comment by jaytaylor** [comment]
(NB: This is from current master)

```(shell)
jay@jays-mba:~/repos/proxychains-ng$ ./configure
checking whether netinet/in.h defines s6_addr16 ... usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix
no
checking whether netinet/in.h defines __u6_addr.__u6_addr16 ... usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix
yes
checking whether $CC defines __OpenBSD__ ... no
Done, now run make && make install
jay@jays-mba:~/repos/proxychains-ng$ make && make install
cc -Qunused-arguments -DSUPER_SECURE -Qunused-arguments -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe -Qunused-arguments -DIS_MAC=1 -DLIB_DIR=\"/usr/local/lib\" -DSYSCONFDIR=\"/usr/local/etc\" -DDLL_NAME=\"libproxychains4.dylib\"  -fPIC -c -o src/nameinfo.o src/nameinfo.c
printf '#define VERSION "%s"\n' "$(sh tools/version.sh)" > src/version.h
cc -Qunused-arguments -DSUPER_SECURE -Qunused-arguments -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe -Qunused-arguments -DIS_MAC=1 -DLIB_DIR=\"/usr/local/lib\" -DSYSCONFDIR=\"/usr/local/etc\" -DDLL_NAME=\"libproxychains4.dylib\"  -fPIC -c -o src/version.o src/version.c
cc -Qunused-arguments -DSUPER_SECURE -Qunused-arguments -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe -Qunused-arguments -DIS_MAC=1 -DLIB_DIR=\"/usr/local/lib\" -DSYSCONFDIR=\"/usr/local/etc\" -DDLL_NAME=\"libproxychains4.dylib\"  -fPIC -c -o src/core.o src/core.c
cc -Qunused-arguments -DSUPER_SECURE -Qunused-arguments -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe -Qunused-arguments -DIS_MAC=1 -DLIB_DIR=\"/usr/local/lib\" -DSYSCONFDIR=\"/usr/local/etc\" -DDLL_NAME=\"libproxychains4.dylib\"  -fPIC -c -o src/common.o src/common.c
cc -Qunused-arguments -DSUPER_SECURE -Qunused-arguments -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe -Qunused-arguments -DIS_MAC=1 -DLIB_DIR=\"/usr/local/lib\" -DSYSCONFDIR=\"/usr/local/etc\" -DDLL_NAME=\"libproxychains4.dylib\"  -fPIC -c -o src/libproxychains.o src/libproxychains.c
src/libproxychains.c:332:12: error: no member named 's6_addr32' in 'struct in6_addr'
        return a->s6_addr32[0] == 0 && a->s6_addr32[1] == 0 &&
               ~  ^
src/libproxychains.c:332:36: error: no member named 's6_addr32' in 'struct in6_addr'
        return a->s6_addr32[0] == 0 && a->s6_addr32[1] == 0 &&
                                       ~  ^
src/libproxychains.c:333:12: error: no member named 's6_addr16' in 'struct in6_addr'
               a->s6_addr16[4] == 0 && a->s6_addr16[5] == 0xffff;
               ~  ^
src/libproxychains.c:333:36: error: no member named 's6_addr16' in 'struct in6_addr'
               a->s6_addr16[4] == 0 && a->s6_addr16[5] == 0xffff;
                                       ~  ^
src/libproxychains.c:363:39: error: no member named 's6_addr32' in 'struct in6_addr'
                memcpy(&v4inv6.s_addr, &p_addr_in6->s6_addr32[3], 4);
                                        ~~~~~~~~~~  ^
/usr/include/secure/_string.h:65:33: note: expanded from macro 'memcpy'
  __builtin___memcpy_chk (dest, src, len, __darwin_obsz0 (dest))
                                ^
src/libproxychains.c:458:63: error: no member named 's6_addr32' in 'struct in6_addr'
                                        memcpy(v4inv6buf, &((struct sockaddr_in6*)sa)->sin6_addr.s6_addr32[3], 4);
                                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/usr/include/secure/_string.h:65:33: note: expanded from macro 'memcpy'
  __builtin___memcpy_chk (dest, src, len, __darwin_obsz0 (dest))
                                ^
6 errors generated.
make: *** [src/libproxychains.o] Error 1
```

**Comment by rofl0r** [comment]
aha, so the bug is that OSX (which version?)'s `mktemp` misbehaves.

**Comment by jaytaylor** [comment]
Yes I agree - this is what appears to be happening.

This is on Mac OS X version 10.9.5.

**Comment by jaytaylor** [comment]
Here is the `configure` output with a `set -x` statement added right before the lines containing `mktemp`:

```(shell)
jay@jays-mba:~/repos/proxychains-ng$ ./configure
+ printf 'checking %s ... ' 'whether netinet/in.h defines s6_addr16'
checking whether netinet/in.h defines s6_addr16 ... ++ mktemp
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix
+ local tmp=
+ printf '#include <netinet/in.h>\nint main(int a, char**c){struct in6_addr x={.s6_addr32[0]=a};return x.s6_addr16[0]; }'
+ local res=0
+ cc -Qunused-arguments -Qunused-arguments -c .c -o .o
+ res=1
+ rm -f .c .o
+ test x1 = x0
+ printf 'no\n'
no
+ return 1
+ check_compile 'whether netinet/in.h defines __u6_addr.__u6_addr16' '-Ds6_addr16=__u6_addr.__u6_addr16 -Ds6_addr32=__u6_addr.__u6_addr32' '#include <netinet/in.h>\nint main(int a, char**c){struct in6_addr x={.s6_addr32[0]=a};return x.s6_addr16[0]; }'
+ set -x
+ printf 'checking %s ... ' 'whether netinet/in.h defines __u6_addr.__u6_addr16'
checking whether netinet/in.h defines __u6_addr.__u6_addr16 ... ++ mktemp
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix
+ local tmp=
+ printf '#include <netinet/in.h>\nint main(int a, char**c){struct in6_addr x={.s6_addr32[0]=a};return x.s6_addr16[0]; }'
+ local res=0
+ cc -Qunused-arguments -Ds6_addr16=__u6_addr.__u6_addr16 -Ds6_addr32=__u6_addr.__u6_addr32 -Qunused-arguments -c .c -o .o
+ rm -f .c .o
+ test x0 = x0
+ printf 'yes\n'
yes
+ test 'x-Ds6_addr16=__u6_addr.__u6_addr16 -Ds6_addr32=__u6_addr.__u6_addr32' = x
+ CPPFLAGS='-Qunused-arguments -Ds6_addr16=__u6_addr.__u6_addr16 -Ds6_addr32=__u6_addr.__u6_addr32'
+ return 0
+ check_define __OpenBSD__
+ printf 'checking whether $CC defines %s ... ' __OpenBSD__
checking whether $CC defines __OpenBSD__ ... + local res=1
+ cc -Qunused-arguments -Ds6_addr16=__u6_addr.__u6_addr16 -Ds6_addr32=__u6_addr.__u6_addr32 -Qunused-arguments -dM -E -
+ grep __OpenBSD__
+ test x1 = x0
+ printf 'no\n'
no
+ return 1
+ echo 'CC?=cc'
+ '[' -z '-Qunused-arguments -Ds6_addr16=__u6_addr.__u6_addr16 -Ds6_addr32=__u6_addr.__u6_addr32' ']'
+ echo 'CPPFLAGS?=-Qunused-arguments' -Ds6_addr16=__u6_addr.__u6_addr16 -Ds6_addr32=__u6_addr.__u6_addr32
+ '[' -z -Qunused-arguments ']'
+ echo 'USER_CFLAGS?=-Qunused-arguments'
+ '[' -z '' ']'
+ echo prefix=/usr/local
+ echo exec_prefix=/usr/local
+ echo bindir=/usr/local/bin
+ echo libdir=/usr/local/lib
+ echo includedir=/usr/local/include
+ echo sysconfdir=/usr/local/etc
+ '[' no = no ']'
+ echo CPPFLAGS+= -DSUPER_SECURE
+ make_cmd=make
+ ismac
+ uname -s
+ grep Darwin
+ echo NO_AS_NEEDED=
+ echo LDSO_SUFFIX=dylib
+ echo MAC_CFLAGS+=-DIS_MAC=1
+ isx86_64
+ uname -m
+ grep -i X86_64
+ '[' '' = 1 ']'
+ echo LD_SET_SONAME=-Wl,-install_name,
+ echo 'Done, now run make && make install'
Done, now run make && make install
```

**Comment by jaytaylor** [comment]
So I changed all `mktemp` commands to `mktemp tmp.XXXXX`, and configure now looks better:

```(shell)
jay@jays-mba:~/repos/proxychains-ng$ ./configure
checking whether netinet/in.h defines s6_addr16 ... no
checking whether netinet/in.h defines __u6_addr.__u6_addr16 ... yes
checking whether $CC defines __OpenBSD__ ... no
Done, now run make && make install
```

But `make` is still upset about `s6_addr32` and `s6_addr16`:

```(shell)
jay@jays-mba:~/repos/proxychains-ng$ make
cc -Qunused-arguments -DSUPER_SECURE -Qunused-arguments -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe -Qunused-arguments -DIS_MAC=1 -DLIB_DIR=\"/usr/local/lib\" -DSYSCONFDIR=\"/usr/local/etc\" -DDLL_NAME=\"libproxychains4.dylib\"  -fPIC -c -o src/nameinfo.o src/nameinfo.c
printf '#define VERSION "%s"\n' "$(sh tools/version.sh)" > src/version.h
cc -Qunused-arguments -DSUPER_SECURE -Qunused-arguments -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe -Qunused-arguments -DIS_MAC=1 -DLIB_DIR=\"/usr/local/lib\" -DSYSCONFDIR=\"/usr/local/etc\" -DDLL_NAME=\"libproxychains4.dylib\"  -fPIC -c -o src/version.o src/version.c
cc -Qunused-arguments -DSUPER_SECURE -Qunused-arguments -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe -Qunused-arguments -DIS_MAC=1 -DLIB_DIR=\"/usr/local/lib\" -DSYSCONFDIR=\"/usr/local/etc\" -DDLL_NAME=\"libproxychains4.dylib\"  -fPIC -c -o src/core.o src/core.c
cc -Qunused-arguments -DSUPER_SECURE -Qunused-arguments -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe -Qunused-arguments -DIS_MAC=1 -DLIB_DIR=\"/usr/local/lib\" -DSYSCONFDIR=\"/usr/local/etc\" -DDLL_NAME=\"libproxychains4.dylib\"  -fPIC -c -o src/common.o src/common.c
cc -Qunused-arguments -DSUPER_SECURE -Qunused-arguments -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe -Qunused-arguments -DIS_MAC=1 -DLIB_DIR=\"/usr/local/lib\" -DSYSCONFDIR=\"/usr/local/etc\" -DDLL_NAME=\"libproxychains4.dylib\"  -fPIC -c -o src/libproxychains.o src/libproxychains.c
src/libproxychains.c:332:12: error: no member named 's6_addr32' in 'struct in6_addr'
        return a->s6_addr32[0] == 0 && a->s6_addr32[1] == 0 &&
               ~  ^
src/libproxychains.c:332:36: error: no member named 's6_addr32' in 'struct in6_addr'
        return a->s6_addr32[0] == 0 && a->s6_addr32[1] == 0 &&
                                       ~  ^
src/libproxychains.c:333:12: error: no member named 's6_addr16' in 'struct in6_addr'
               a->s6_addr16[4] == 0 && a->s6_addr16[5] == 0xffff;
               ~  ^
src/libproxychains.c:333:36: error: no member named 's6_addr16' in 'struct in6_addr'
               a->s6_addr16[4] == 0 && a->s6_addr16[5] == 0xffff;
                                       ~  ^
src/libproxychains.c:363:39: error: no member named 's6_addr32' in 'struct in6_addr'
                memcpy(&v4inv6.s_addr, &p_addr_in6->s6_addr32[3], 4);
                                        ~~~~~~~~~~  ^
/usr/include/secure/_string.h:65:33: note: expanded from macro 'memcpy'
  __builtin___memcpy_chk (dest, src, len, __darwin_obsz0 (dest))
                                ^
src/libproxychains.c:458:63: error: no member named 's6_addr32' in 'struct in6_addr'
                                        memcpy(v4inv6buf, &((struct sockaddr_in6*)sa)->sin6_addr.s6_addr32[3], 4);
                                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/usr/include/secure/_string.h:65:33: note: expanded from macro 'memcpy'
  __builtin___memcpy_chk (dest, src, len, __darwin_obsz0 (dest))
                                ^
6 errors generated.
make: *** [src/libproxychains.o] Error 1
```

**Comment by jaytaylor** [comment]
What does it try to do when `s6_addr16` is not defined by netinet/in.h?

**Comment by jaytaylor** [comment]
Because all I see is:

```(shell)
check_compile 'whether netinet/in.h defines s6_addr16' "" \
'#include <netinet/in.h>\nint main(int a, char**c){struct in6_addr x={.s6_addr32[0]=a};return x.s6_addr16[0]; }' \
|| {
check_compile 'whether netinet/in.h defines __u6_addr.__u6_addr16' \
'-Ds6_addr16=__u6_addr.__u6_addr16 -Ds6_addr32=__u6_addr.__u6_addr32' \
'#include <netinet/in.h>\nint main(int a, char**c){struct in6_addr x={.s6_addr32[0]=a};return x.s6_addr16[0]; }'
}
```

Which, if I understand correctly, doesn't do anything other than print a message about it?

**Comment by rofl0r** [comment]
it should add `'-Ds6_addr16=__u6_addr.__u6_addr16 -Ds6_addr32=__u6_addr.__u6_addr32'` to your CFLAGS in config.mak
can you paste your config.mak ?

**Comment by jaytaylor** [comment]
```(shell)
jay@jays-mba:~/repos/proxychains-ng$ cat config.mak
CC?=cc
CPPFLAGS?=-Qunused-arguments -Ds6_addr16=__u6_addr.__u6_addr16 -Ds6_addr32=__u6_addr.__u6_addr32
USER_CFLAGS?=-Qunused-arguments
prefix=/usr/local
exec_prefix=/usr/local
bindir=/usr/local/bin
libdir=/usr/local/lib
includedir=/usr/local/include
sysconfdir=/usr/local/etc
CPPFLAGS+= -DSUPER_SECURE
NO_AS_NEEDED=
LDSO_SUFFIX=dylib
MAC_CFLAGS+=-DIS_MAC=1
LD_SET_SONAME=-Wl,-install_name,
```

**Comment by jaytaylor** [comment]
```(shell)
jay@jays-mba:~/repos/proxychains-ng$ make
printf '#define VERSION "%s"\n' "$(sh tools/version.sh)" > src/version.h
cc -Qunused-arguments -DSUPER_SECURE -Qunused-arguments -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe -Qunused-arguments -DIS_MAC=1 -DLIB_DIR=\"/usr/local/lib\" -DSYSCONFDIR=\"/usr/local/etc\" -DDLL_NAME=\"libproxychains4.dylib\"  -fPIC -c -o src/version.o src/version.c
cc -Qunused-arguments -DSUPER_SECURE -Qunused-arguments -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe -Qunused-arguments -DIS_MAC=1 -DLIB_DIR=\"/usr/local/lib\" -DSYSCONFDIR=\"/usr/local/etc\" -DDLL_NAME=\"libproxychains4.dylib\"  -fPIC -c -o src/libproxychains.o src/libproxychains.c
src/libproxychains.c:332:12: error: no member named 's6_addr32' in 'struct in6_addr'
        return a->s6_addr32[0] == 0 && a->s6_addr32[1] == 0 &&
               ~  ^
src/libproxychains.c:332:36: error: no member named 's6_addr32' in 'struct in6_addr'
        return a->s6_addr32[0] == 0 && a->s6_addr32[1] == 0 &&
                                       ~  ^
src/libproxychains.c:333:12: error: no member named 's6_addr16' in 'struct in6_addr'
               a->s6_addr16[4] == 0 && a->s6_addr16[5] == 0xffff;
               ~  ^
src/libproxychains.c:333:36: error: no member named 's6_addr16' in 'struct in6_addr'
               a->s6_addr16[4] == 0 && a->s6_addr16[5] == 0xffff;
                                       ~  ^
src/libproxychains.c:363:39: error: no member named 's6_addr32' in 'struct in6_addr'
                memcpy(&v4inv6.s_addr, &p_addr_in6->s6_addr32[3], 4);
                                        ~~~~~~~~~~  ^
/usr/include/secure/_string.h:65:33: note: expanded from macro 'memcpy'
  __builtin___memcpy_chk (dest, src, len, __darwin_obsz0 (dest))
                                ^
src/libproxychains.c:458:63: error: no member named 's6_addr32' in 'struct in6_addr'
                                        memcpy(v4inv6buf, &((struct sockaddr_in6*)sa)->sin6_addr.s6_addr32[3], 4);
                                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/usr/include/secure/_string.h:65:33: note: expanded from macro 'memcpy'
  __builtin___memcpy_chk (dest, src, len, __darwin_obsz0 (dest))
                                ^
6 errors generated.
make: *** [src/libproxychains.o] Error 1
```

**Comment by jaytaylor** [comment]
I think I just figured it out!

From the output of `make` the runtime contents of `$(CPPFLAGS)` are revealed:

    cc -Qunused-arguments -DSUPER_SECURE -Qunused-arguments \
        -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe -Qunused-arguments \
        -DIS_MAC=1 -DLIB_DIR=\"/usr/local/lib\" \
        -DSYSCONFDIR=\"/usr/local/etc\" -DDLL_NAME=\"libproxychains4.dylib\" \
        -fPIC -c -o src/version.o src/version.c

`$(CPPFLAGS)` contains only "-DSUPER_SECURE" and has nothing about `-Ds6_addr...`.  Let's look see what's happened from `config.mak`:

```(shell)
CPPFLAGS?=-Qunused-arguments -Ds6_addr16=__u6_addr.__u6_addr16 -Ds6_addr32=__u6_addr.__u6_addr32
...
CPPFLAGS+= -DSUPER_SECURE
```

From [Makefile variable assignment](http://stackoverflow.com/questions/448910/makefile-variable-assignment):

> *Set If Absent*
> 
>     VARIABLE ?= value
> 
> Setting of a variable only if it doesn't have a value

The output observed suggests the order of evaluation when `config.mak` is included is not from the beginning of the file to the end (otherwise the `$(CPPFLAGS)` variable would contain what we expect and the thing would compile!).

Order of evaluation:

1st statement: `CPPFLAGS+= -DSUPER_SECURE`
$(CPPFLAGS) Contents: ` -DSUPER_SECURE`

1nd evaluated statement: `CPPFLAGS?=-Qunused-arguments -Ds6_addr16=__u6_addr.__u6_addr16 -Ds6_addr32=__u6_addr.__u6_addr32`
$(CPPFLAGS) Contents: ` -DSUPER_SECURE`

(Statement has no effect.)

A straightforward way to fix it is to change `?=` to `+= `.

I'll adjust the PR accordingly, and include a fix for the `mktemp` issue.

**Comment by jaytaylor** [comment]
@rofl0r Thank you so much for being so responsive on this issue!  I believe this PR is in good shape, looking forward to your feedback.

I've tested it on the Mac and Linux and now both build and work without issue. :)

Cheers!

**Comment by rofl0r** [comment]
just to make sure: did you have exported CPPFLAGS on your system ?
you can run `echo $CPPFLAGS` in your shell to find out.

**Comment by jaytaylor** [comment]
@rofl0r Nice catch! I'd forgotten about this stanza in my `.bashrc`:

```(shell)
# <C++>
# These exports are to avoid clang compilation problems as per
# http://stackoverflow.com/questions/22313407/clang-error-unknown-argument-mno-fused-madd-python-package-installation
export CFLAGS=-Qunused-arguments
export CPPFLAGS=-Qunused-arguments
# </C++>
```

I still believe it'd be best to switch to appending to CPPFLAGS, unless there is something else I've overlooked.

**Comment by rofl0r** [comment]
so yeah, in that case the problem was because your CPPFLAGS were overriding the ones set by the build system. this is intentional because we want to mimick autoconf behaviour as nearly as possible. in this case though the s6_addr32 macro is essential to compilation so it doesn't make sense to make it overridable. i'll think about it some more to find a clean fix. I disagree with the removal of config.mak: it is against the users expectation (at least if he's used to autoconf) that `make clean` will remove his configuration and he will have to re-run `configure`!

**Comment by rofl0r** [comment]
hello @jaytaylor , could you test my commit in the branch OUR_CPPFLAGS and report if that closes this issue ? thanks!

**Comment by jaytaylor** [comment]
Hey @rofl0r,

The OUR_CPPFLAGS branch works nicely for me!  I also like this solution, it is a nice, clean approach to avoid the `$CPPFLAGS` variable conflict entirely.

Cheers,
Jay

**Comment by jaytaylor** [comment]
@rofl0r FYI, I believe I've removed all controversial commits so you can merge this PR.

**Comment by rofl0r** [comment]
@jaytaylor thanks for testing!
as for merging this PR: aren't we done yet ? or have i overlooked something essential apart from your personal vim config ?

**Comment by jaytaylor** [comment]
Haha, nothing essential.  Just my (fairly standard I think) vim ignores and the dylib ignore.

**Comment by rofl0r** [comment]
well if you care enough, please make another clean PR on top of current master, so we can keep the commit history straight.
cheers!

**Pull request closed without merging**
