### PR TITLE
core.c: add HOST header to each CONNECT request

### LINKED ISSUE #92: Incompatibility due to missing Host header while in HTTPS mode
Proxychains-ng in HTTPS mode doesn't send Host header.
This leads to compatibility issues with poorly written proxies.
For example @citrix Access Gateway's Java Applet Client fails with "HTTP/1.1 400 Bad Request" for CONNECT method requests unless Host header is passed, even though requests are coming as  HTTP/1.0.

One of the workaround would be to always pass Host header with every request.

### PR DESCRIPTION
**Pull request by forkbomber**
fixes #92

### CODE REVIEW

**Comment by rofl0r** [comment]
i think as-is, this patch would create more problems than it solves, since this way we're basically sending an incorrect/hackish http 1.0 header.
a cleaner solution would be if we add a new proxytype in the config file ( http11)
(and possibly http10 as an alias for http)
and if it's used send a HTTP/1.1 header with hosts line, if not HTTP/1.0 without it.

**Comment by forkbomber** [comment]
True, HTTP 1.0 doesn't require Host header.
At the same time this is exactly how browsers sends HTTPS CONNECT requests to proxies.

Below are two tests I run today:

* Firefox
    ```
    CONNECT github.com:443 HTTP/1.0
    User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:41.0) Gecko/20100101 Firefox/41.0
    Proxy-Connection: keep-alive
    Connection: keep-alive
    Host: github.com:443
    ```

* Internet Explorer
    ```
    CONNECT github.com:443 HTTP/1.0
    User-Agent: Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0)
    Proxy-Connection: Keep-Alive
    Content-Length: 0
    Host: github.com
    Pragma: no-cache
    ```

I agree that changes like this might introduce some compatibility issues.

At the same its hard to imaging many proxy servers in the wild which would be confused by HTTP/1.0 CONNECT requests with Host header, since this is exactly how major browsers used to send requests not long ago (these days they send HTTP/1.1 even for CONNECT requests to proxies unless forced HTTP/1.0).

In a long term proxychains might be better off mimicking requests of major browsers, since they are THE testing target for http proxies / http servers. That would ensure greater compatibility and prevent issues similar to #92.

**Comment by rofl0r** [comment]
i guess i'll do a release first with the new ipv6 support and then merge the patch as-is or like i proposed. that way users of the git version can test if the change causes breakage.

**Comment by ilyaglow** [comment]
I'm working on similar thing right now and actually HTTP/1.0 specification hasn't CONNECT method at all: https://tools.ietf.org/html/rfc1945#section-8

Making CONNECT with HTTP/1.0 is just a kind of backward compatibility echo from the past, temporary transition from HTTP/1.0 to HTTP/1.1 (how proxychains even got this implemented?), btw such as Netscape's "Proxy-Connection: Keep-Alive" header. The latest stable Squid proxy server and couple of others won't let you tunnel like that.

So HTTP/1.0 doesn't suppose to have persistent connections and probably should be vanished from proxychains completely.

**Comment by rofl0r** [comment]
merged at last... it remains to be seen if we should bump the HTTP version to 1.1 as well.

**Pull request closed without merging**
