### PR TITLE
Add dnat feature

### PR DESCRIPTION
**Pull request by tomgilon**
Add the option to change the destination ip and port before sending them to the proxy server.

### CODE REVIEW

**Comment by rofl0r** [comment]
@tomgilon why was this PR closed ? i didn't have time to check github lately if it was due to lack of a timely response

**Comment by tomgilon** [comment]
Wasn't sure which one of the proxychains repos is the correct one.
I have an updated version of this pr ill reopen tomorrow

**Comment by tomgilon** [comment]
@rofl0r ?

**Comment by rofl0r** [comment]
LGTM

**Pull request merged**
