### PR TITLE
some fixes..

### PR DESCRIPTION
**Pull request by ordex**

### CODE REVIEW

**Comment by ordex** [comment]
anybody interested in reviewing this PR?

**Comment by rofl0r** [comment]
i merged the mem-leak commit, good find. as for the 2nd commit, i don't see a good reason why we should protect the user from himself.

**Comment by ordex** [comment]
I personally think the second commit makes sense because the user is not aware of the limit and a crash won't help understanding. Avoid the crash and warning the user is more reasonable I think.

**Comment by ordex** [comment]
that also makes sense

**Comment by rofl0r** [comment]
ok, can you please open a new PR with the suggested change ? thanks

**Comment by ordex** [comment]
will do, thanks!

**Pull request closed without merging**
